# Generated by Django 5.2.12 on 2026-04-27 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.specialty', verbose_name="Yo'nalish"),
        ),
    ]
